baseurl: ""
exclude: ["README.md"]
permalink: pretty
title: "Growth Through Empathy"
collections_dir: collections
markdown: kramdown
remote_theme: jekyll-advance-pro

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

collections:
  services:
    output: true
    permalink: /:collection/:path/
  work:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
  - scope:
      type: work
    values:
      layout: work
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

params:
  google_analytics_id: ""
  global:
    header_fixed: false
  footer:
    show_menu_footer_primary: true
    show_menu_footer_secondary: false
    show_services_links: false
    show_work_links: false
  homepage:
    show_services_section: true
    services_count: 2
    show_splash_section_one: true
    splash_one_image: assets/images/GTE-Aug.png
    splash_one_heading: This months webinar
    splash_one_paragraph: During this webinar, Experiment Zone and The Freed Agency will be giving actionable recommendations to real brands. You'll learn from grounded and real examples how you can improve your marketing efforts and make more revenue.<br><br>What will you learn?<br> - About the importance of incorporating purpose and empathy in your marketing.<br> - Ways to use empathy to improve customer experiences & conversion rates.
    splash_one_link_url: "https://calendly.com/experimentzone/growth-through-empathy-free-marketing-webinar?month=2020-08"
    splash_one_link_text: Sign Up
    show_partners: true
    show_work_section: false
    work_section_heading: Upcoming Events
    work_count: 2
    show_view_all_work_button: false
  services:
    show_features: true
    show_splash_one_section: true
    splash_one_background_image: assets/images/kaleidico-754543-unsplash.jpg
    splash_one_heading: We build great software
    splash_one_paragraph:
      Lorem ipsum dolor sit amet, et essent mediocritatem quo, choro volumus
      oporteat an mei. Numquam dolores mel eu, mea docendi omittantur et, mea ea
      duis erat. Elit melius cu ius. Per ex novum tantas putant, ei his nullam
      aliquam apeirian. Aeterno quaestio constituto sea an, no eum intellegat
      assueverit.
  contact_cta:
    heading: Ready to get started?
    subheading: Get in touch and get a quote.
    button_url: contact
    button_text: Contact us

plugins:
  - jekyll-environment-variables

theme: jekyll-theme-cayman
